Javaフレームワーク 最終課題の実装
murakami29/SpringBootPractice pull request #6
Opened 2024-07-15 04:40 UTC by murakami29

# Java フレームワーク編
SpringBootPracticeリポジトリの提出
・作業ブランチ名: add-admin

# やったこと
Javaフレームワーク 最終課題を実装し、コミットしました。
ご確認よろしくお願いします。

2024-07-16 02:14 UTC, y0sh1ka2u commented on practice/src/main/java/com/example/demo/service/AdminServiceImpl.java
> +        adminRepository.save(admin);
インデントの修正をお願いします！

2024-07-16 02:14 UTC, y0sh1ka2u commented on practice/src/main/java/com/example/demo/service/ContactServiceImpl.java
> +	@Override
Overrideのアノテーションのインデント修正お願いします

2024-07-16 02:14 UTC, y0sh1ka2u commented on practice/pom.xml
> +	    </dependency>
この依存関係は今回の実装において、何をするために使ってますでしょうか？

2024-07-16 05:18 UTC, murakami29 commented on practice/src/main/java/com/example/demo/service/AdminServiceImpl.java
> +        adminRepository.save(admin);
確認させてください。インデントの修正はスペース4つでインデントするように修正するという認識であっていますでしょうか。

2024-07-16 05:24 UTC, murakami29 commented on practice/pom.xml
> +	    </dependency>
エラー解消の際、テストコードを使用して原因確認をするために、依存関係を記載したものです。
実装においては不要のため、削除いたします。

2024-07-17 00:49 UTC, uchiyama4929 requested changes

2024-07-17 00:49 UTC, uchiyama4929 commented on practice/src/main/java/com/example/demo/controller/AdminController.java
> +            return "admin/contactEdit";
バリデーションがかかっていなくて空の状態でも処理が動いてしまうようです。

2024-07-17 00:49 UTC, uchiyama4929 commented on practice/src/main/java/com/example/demo/controller/AdminController.java
> +            return "admin/error";
admin/errorという画面が存在しなくてエラーになるようです。

2024-07-21 04:08 UTC, merged